<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Struk Transaksi</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .container { width: 100%; max-width: 300px; margin: 0 auto; }
        .header { text-align: center; margin-bottom: 10px; }
        .header h1 { margin: 0; font-size: 20px; }
        .header h2 { margin: 0; font-size: 14px; }
        .header p { margin: 0; font-size: 10px; }
        hr { border: none; border-top: 1px dashed #000; margin: 5px 0; }
        .content { margin-bottom: 10px; }
        .content p { margin: 3px 0; font-size: 12px; }
        .footer { text-align: center; margin-top: 10px; font-size: 10px; }
    </style>
    <script type="text/javascript">
        function triggerPrint() {
            window.print();
        }
    </script>
</head>
<body onload="triggerPrint()">
    <div class="container">
        <div class="header">
            <h1>BreakRoom</h1>
            <h2>Jl.Simpang Golf Kav.11, Malang, Jawa Timur</h2>
            <p>Telepon: (021) 8976542456 | Email: breakroom@idn.com</p>
        </div>
        <hr/>
        <center><h3>Struk Transaksi</h3></center>
        <div class="content">
            <p><strong>ID Transaksi:</strong> {{ $transaction_info['id_trxTableBilliard'] }}</p>
            <p><strong>Nama Member:</strong> {{ $member_name }}</p>
            <p><strong>ID Pemesanan Meja:</strong> {{ $transaction_info['id_trxTableBilliard'] }}</p>
            <p><strong>Tanggal Checkout:</strong> {{ $transaction_info['Date_checkout'] }}</p>
            <p><strong>Waktu Checkout:</strong> {{ $transaction_info['Time_checkout'] }}</p>
            <p><strong>Jumlah Pembayaran:</strong> Rp {{ number_format($transaction_info['Amount'], 0, ',', '.') }}</p>
        </div>
        <hr/>
        <div class="footer">
            <p>Grettings Billiards Without Gambling!!</p>
            <hr/>
            <hr/>
            <p>Generated by BreakRoom.idn | {{ date('Y-m-d') }}</p>
        </div>
    </div>
</body>
</html>
